### ISSUE TITLE
I am trying to use this keyward asyn run 

### ISSUE THREAD

**Issue by jaehokim00** [Chetic/robotframework-async#1]
after I install and when I run ...

```
  ${handle}=      async run       Check Apid In Kafka 
```

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/Library/Python/2.6/site-packages/AsyncLibrary/async.py", line 43, in wrapped_f
    ret = f.run(EXECUTION_CONTEXTS.current, args)
  File "/Library/Python/2.6/site-packages/robot/running/userkeyword.py", line 140, in run
    return self._run(context, arguments)
  File "/Library/Python/2.6/site-packages/robot/running/userkeyword.py", line 147, in _run
    return self._normal_run(context, arguments)
  File "/Library/Python/2.6/site-packages/robot/running/userkeyword.py", line 158, in _normal_run
    error, return_ = self._execute(context, arguments)
  File "/Library/Python/2.6/site-packages/robot/running/userkeyword.py", line 178, in _execute
    self.timeout.start()

it would great if it runs well..

**Comment by jaehokim00** [comment]
just FYI,,,

Robot Framework 2.8.7 (Python 2.6.9 on darwin) is my pybot version...

**Comment by fa1k3n** [comment]
eh, does the "Check Apid In Kafka" keyword run without async? Post the code for this please
