### ISSUE TITLE
traceback with Asynch Run

### ISSUE THREAD

**Issue by cunningr** [Chetic/robotframework-async#9]
I am trying to use this library for async execution of keywords but I get a traceback;

*** Test Cases ***

Discover device under test platform type
  ${handle}  async run  Discover device under test platform type
  ${return_value}  async get ${handle}

root@72ddb142860f:/home/cisco/cxta# robot underlay/POD1-FB-01_underlay.robot
==============================================================================
POD1-FB-01 underlay
==============================================================================
Discover device under test platform type                              .Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/venv/lib/python3.7/site-packages/AsyncLibrary/robot_async.py", line 45, in wrapped_f
    f = self._get_handler_from_keyword(keyword)
  File "/venv/lib/python3.7/site-packages/AsyncLibrary/robot_async.py", line 34, in _get_handler_from_keyword
    return EXECUTION_CONTEXTS.current.get_handler(keyword)
AttributeError: '_ExecutionContext' object has no attribute 'get_handler'

I am probably doing something stupid but I can't find much help out in the wild.

**Comment by rlehfeld** [comment]
I think the implementation in robot framework changed. There is no longer a get_handler method.
I forked the library and did the necessary adaptations. You can find my fork here:

https://github.com/rlehfeld/robotframework-async-keyword.git
